# Generated by Django 3.1.3 on 2020-11-04 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullorder',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='recepient_fullname',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='state',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='zipcode',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
