# Generated by Django 3.1.3 on 2020-11-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201104_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_item',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
